### PR TITLE
Tenants

### PR DESCRIPTION
**Pull request by strangiato**
Migrate namespace configs to utilize gitops-tenant helm chart.

This should be a one for one replacement of the existing namespaces + rbac and should give some additional flexibility for future managed resources and improved configuration of the namespaces.

### CODE REVIEW

**Comment by codekow** [comment]
@strangiato - Lots of forward looking changes :)

- Do we want to remain consistent on `hou-edge` vs `hou-lab`?
- Do we need `.helmignore` in every tenant folder?

Let's find a time to interactively review the changes / dependencies.

**Review by codekow — COMMENTED** [review]
Most of the changes make sense.

For consistency do we want `hou-edge` vs `hou-lab under tentants?

**Comment by strangiato** [comment]
Good catch on the edge vs lab.  I was just reusing whatever was there.  Which do you prefer?

**Review by codekow — APPROVED** [review]
Fridays are the best day to merge major changes :)

**Comment by codekow** [comment]
@strangiato Feel free to merge in when you have time (hopefully there is minimal troubleshooting).

**Pull request merged**
